apiVersion: v1
kind: Namespace
metadata:
  name: minio-preprod

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: minio-storage
  namespace: minio-preprod
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
  namespace: minio-preprod
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: minio-storage
  local:
    path: /home/minio-storage
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - node1

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-preprod
  namespace: minio-preprod
spec:
  storageClassName: minio-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi